steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast3-docker.pkg.dev/complete-tube-420605/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'push', 'asia-northeast3-docker.pkg.dev/complete-tube-420605/reservations/production' ]
  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast3-docker.pkg.dev/complete-tube-420605/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'push', 'asia-northeast3-docker.pkg.dev/complete-tube-420605/auth/production' ]
  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast3-docker.pkg.dev/complete-tube-420605/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'push', 'asia-northeast3-docker.pkg.dev/complete-tube-420605/notifications/production' ]
  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast3-docker.pkg.dev/complete-tube-420605/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.',
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'push', 'asia-northeast3-docker.pkg.dev/complete-tube-420605/payments/production' ]
